### ISSUE TITLE
Markdown cleanup for contributing-to-the-repository.md

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily-manual#3]
In https://github.com/margaritahumanitarian/helpafamily-manual/blob/main/contributing-to-the-repository.md

- [ ] Correct the numbered list indentation
- [ ] Correct the code block indentation
- [ ] Make sure fenced code blocks have the language next to the 3 backticks
- [ ] Under "Making changes locally and creating a pull request:" convert inline code blocks to fenced code blocks

**Comment by ozer550** [comment]
I would like to work on this.

**Comment by audreyfeldroy** [comment]
Merged in #5, I appreciate your work @ozer619!
