### ISSUE TITLE
Link to https://margaritahumanitarian.gitbook.io/help-a-family-manual/ from main repos' READMEs

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily-manual#4]
In both READMEs for both repos, link to https://margaritahumanitarian.gitbook.io/help-a-family-manual/

- [ ] https://github.com/margaritahumanitarian/helpafamily-manual/blob/main/README.md
- [ ] https://github.com/margaritahumanitarian/helpafamily/blob/main/README.md

**Comment by ozer550** [comment]
I would like to work on this.

**Comment by audreyfeldroy** [comment]
Merged in #6 and https://github.com/margaritahumanitarian/helpafamily/pull/180 - thanks @ozer619!
